name: Feature Request
description: Suggest an enhancement or new feature
labels: [enhancement]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What would you like doxr to do?
    validations:
      required: true
